In [1]:
import torch
from torch import nn
import torch.nn.functional as F

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
with open('../Data/shakespeare.txt','r',encoding='utf8') as f:
    text = f.read()

In [4]:
type(text)

str

In [5]:
print(text[:1000])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [6]:
len(text)

5445609

In [7]:
all_characters = set(text)

In [8]:
len(all_characters)

84

In [9]:
# number of value ---> letter
decoder = dict(enumerate(all_characters))

In [10]:
#decoder

In [11]:
# letter ---> corresponding number
encoder = {char: idx for idx,char in decoder.items()}

In [12]:
#encoder

In [13]:
encoded_text = np.array([encoder[char] for char in text])

In [14]:
encoded_text[:500]

array([83, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
       43, 43, 43, 43, 43, 72, 83, 43, 43, 67, 35, 44, 82, 43, 21, 22, 77,
       35, 50, 62, 31, 43, 42, 35, 50, 22, 31, 65, 35, 50, 62, 43,  7, 50,
       43, 69, 50, 62, 77, 35, 50, 43, 77, 73, 42, 35, 50, 22, 62, 50, 38,
       83, 43, 43, 59, 34, 22, 31, 43, 31, 34, 50, 35, 50, 15, 53, 43, 15,
       50, 22, 65, 31, 53, 54, 62, 43, 35, 44, 62, 50, 43, 82, 77, 63, 34,
       31, 43, 73, 50, 13, 50, 35, 43, 69, 77, 50, 38, 83, 43, 43, 18, 65,
       31, 43, 22, 62, 43, 31, 34, 50, 43, 35, 77, 55, 50, 35, 43, 62, 34,
       44, 65, 29, 69, 43, 15, 53, 43, 31, 77, 82, 50, 43, 69, 50, 42, 50,
       22, 62, 50, 38, 83, 43, 43, 56, 77, 62, 43, 31, 50, 73, 69, 50, 35,
       43, 34, 50, 77, 35, 43, 82, 77, 63, 34, 31, 43, 15, 50, 22, 35, 43,
       34, 77, 62, 43, 82, 50, 82, 44, 35, 53, 11, 83, 43, 43, 18, 65, 31,
       43, 31, 34, 44, 65, 43, 42, 44, 73, 31, 35, 22, 42, 31, 50, 69, 43,
       31, 44, 43, 31, 34

In [16]:
decoder[43]

' '

In [23]:
def one_hot_encoder(encoded_text, num_uni_chars):
    # encoded text ---> batch of encoded text
    # num_uni_chars ---> len(set(text))

    one_hot = np.zeros((encoded_text.size, num_uni_chars))

    # convert data type
    one_hot = one_hot.astype(np.float32)

    # set values to 1 for each corresponding character (i.e. 0, 0, 0, 0, ..., 1(43rd position), 0, 0, ...) for ' ' (space)
    one_hot[np.arange(one_hot.shape[0]), encoded_text.flatten()] = 1.0

    one_hot = one_hot.reshape((*encoded_text.shape, num_uni_chars))

    return one_hot

In [20]:
arr = np.array([1,2,0])

In [21]:
arr

array([1, 2, 0])

In [25]:
# for idx 1 of row 1 -> 1, idx 2 of row 2 -> 1, and idx 0 of row 2 -> 1
one_hot_encoder(arr, 3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)